[atom]
id = "mkHorizon"
version = "0.1.0"
propagate = true
src = "atom"

[features]
default = ["lib", "pkgs"]

[backend.nix]
fetcher = "flake-lock"

[fetch.rust-atom]

[fetch.horizon-rs]
type = "src"
